# Generated by Django 5.1.5 on 2025-03-09 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='action',
            name='context',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='search_query',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='search_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('like', 'Like'), ('save', 'Save'), ('play', 'Play'), ('skip', 'Skip'), ('view', 'View'), ('share', 'Share'), ('complete', 'Complete'), ('search', 'Search')], max_length=10),
        ),
        migrations.AlterField(
            model_name='action',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_actions', to='app.song'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['user', 'action_type'], name='app_action_user_id_9d9f22_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['song', 'action_type'], name='app_action_song_id_975a17_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['timestamp'], name='app_action_timesta_5c6884_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['search_query'], name='app_action_search__3abecd_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['search_type'], name='app_action_search__fedd36_idx'),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.UniqueConstraint(condition=models.Q(('action_type', 'search'), _negated=True), fields=('user', 'song', 'action_type'), name='unique_non_search_action'),
        ),
    ]
