# Generated by Django 5.1.5 on 2025-03-15 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistsong',
            options={'ordering': ['-added_at']},
        ),
        migrations.RemoveIndex(
            model_name='playlistsong',
            name='app_playlis_playlis_c26b07_idx',
        ),
        migrations.RemoveIndex(
            model_name='playlistsong',
            name='app_playlis_song_id_007138_idx',
        ),
        migrations.AlterField(
            model_name='playlistsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='app.song'),
        ),
    ]
