# Generated by Django 5.1.6 on 2025-03-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_song_userprofile_history_userprofile_preferences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='song',
        ),
        migrations.AddField(
            model_name='action',
            name='spotify_id',
            field=models.CharField(default='unkown', max_length=255),
        ),
    ]
