# Generated by Django 5.1.5 on 2025-03-02 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_esewapayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('user', 'song', 'action_type')},
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['user', 'song', 'action_type'], name='app_action_user_id_5f7a4a_idx'),
        ),
    ]
