# Generated by Django 5.1.5 on 2025-03-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_playlist_playlistsong_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='spotify_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='spotify_token',
        ),
    ]
