# Generated by Django 5.1.5 on 2025-04-04 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danceability', models.FloatField(default=0)),
                ('energy', models.FloatField(default=0)),
                ('key', models.IntegerField(default=0)),
                ('loudness', models.FloatField(default=0)),
                ('mode', models.IntegerField(default=0)),
                ('speechiness', models.FloatField(default=0)),
                ('acousticness', models.FloatField(default=0)),
                ('instrumentalness', models.FloatField(default=0)),
                ('liveness', models.FloatField(default=0)),
                ('valence', models.FloatField(default=0)),
                ('tempo', models.FloatField(default=0)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_features', to='app.song')),
            ],
        ),
    ]
