# Generated by Django 5.1.5 on 2025-03-03 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_action_song_action_spotify_id'),
        ('app', '0006_song_url'),
    ]

    operations = [
    ]
