# Generated by Django 5.1.5 on 2025-04-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_audiofeatures'),
        ('app', '0008_remove_contactrequest_attachment'),
    ]

    operations = [
    ]
