# Generated by Django 5.1.5 on 2025-04-13 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20250411_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_date', models.DateField()),
                ('chart_type', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('streams', models.BigIntegerField(blank=True, null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_entries', to='app.song')),
            ],
            options={
                'unique_together': {('chart_date', 'chart_type', 'song')},
            },
        ),
        migrations.CreateModel(
            name='ChartSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_date', models.DateField()),
                ('chart_type', models.CharField(max_length=50)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('chart_date', 'chart_type')},
            },
        ),
        migrations.DeleteModel(
            name='AudioFeatures',
        ),
    ]
