# Generated by Django 5.1.5 on 2025-04-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_chartentry_chartsnapshot_delete_audiofeatures'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chartentry',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='chartentry',
            name='song',
        ),
        migrations.DeleteModel(
            name='ChartSnapshot',
        ),
        migrations.DeleteModel(
            name='ChartEntry',
        ),
    ]
